### PR TITLE
Update Lambda's Node.js version and dependencies

### PR DESCRIPTION
**Pull request by adwd**
Hello.
This PR updates the LogNotifier Lambda from Node.js 18 to 20. In addition, I updated the version of the dependent libraries.
I have added snapshot tests and can see the changes from each update from the snapshot, but I don't think there are any problems.

### CODE REVIEW

**Comment by acomagu** [comment]
Looks good. Thanks!

**Comment by acomagu** [comment]
@adwd Hi, I'd like to specify NODEJS_LATEST instead of NODEJS_20 if that's ok with you, do you have any concerns?

**Comment by adwd** [comment]
@acomagu I think it is good 🚀

**Comment by acomagu** [comment]
2.1.0 Released.

**Pull request merged**
